// Code generated by options-gen. DO NOT EDIT.
package phonevalidator

import (
	fmt461e464ebed9 "fmt"
	"time"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"go.temporal.io/sdk/client"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	temporalClient client.Client,
	callProvider string,
	smsProvider string,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)
	o.poolingTimeout, _ = time.ParseDuration("100ms")
	o.workflowExecTimeout, _ = time.ParseDuration("600s")

	o.temporalClient = temporalClient
	o.callProvider = callProvider
	o.smsProvider = smsProvider

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithPoolingTimeout(opt time.Duration) OptOptionsSetter {
	return func(o *Options) {
		o.poolingTimeout = opt
	}
}

func WithWorkflowExecTimeout(opt time.Duration) OptOptionsSetter {
	return func(o *Options) {
		o.workflowExecTimeout = opt
	}
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("temporalClient", _validate_Options_temporalClient(o)))
	errs.Add(errors461e464ebed9.NewValidationError("callProvider", _validate_Options_callProvider(o)))
	errs.Add(errors461e464ebed9.NewValidationError("smsProvider", _validate_Options_smsProvider(o)))
	return errs.AsError()
}

func _validate_Options_temporalClient(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.temporalClient, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `temporalClient` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_callProvider(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.callProvider, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `callProvider` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_smsProvider(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.smsProvider, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `smsProvider` did not pass the test: %w", err)
	}
	return nil
}
