// Code generated by options-gen. DO NOT EDIT.
package activities

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptCallOptionsSetter func(o *CallOptions)

func NewCallOptions(
	defaultGateway string,
	options ...OptCallOptionsSetter,
) CallOptions {
	o := CallOptions{}

	// Setting defaults from field tag (if present)

	o.defaultGateway = defaultGateway

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *CallOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("defaultGateway", _validate_CallOptions_defaultGateway(o)))
	return errs.AsError()
}

func _validate_CallOptions_defaultGateway(o *CallOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.defaultGateway, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `defaultGateway` did not pass the test: %w", err)
	}
	return nil
}
